server:
  port: 8080

#数据源
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zmj-frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    #集成druid监控sql页面
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
#redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    #连接池，这里用lettuce，不用jedis
    lettuce:
      pool:
        #最大连接数
        max-active: 20
        max-idle: 8
        max-wait: -1
        min-idle: 0

#sqlbeauty开关
switch:
  beauty:
    show: true

#mybatis plus逻辑删除拦截器
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

#swagger配置
swagger:
  base-package: com.zmj
  title: zmj-frame
  contact-url: https://github.com/ZMJ-Java/zmj-frame
  email: 1486480852@qq.com
  description: 从0到1开发一个框架

#log4j配置
logging:
  config: classpath:log4j-spring.xml
log:
  aspect:
    enable: true

#
guava:
  cache:
    switch: true

